deploy to production:
 stage: deploy
 only:
  - main
 environment:
  name: production
 variables:
  WWW: "/home/www/echa_mcp"
  USER: "root"
  SERVER: "192.168.18.200"
 script:
  - rsync -arvzuq --progress --exclude ".git"  --exclude ".gitignore" --exclude ".gitlab-ci.yml"  --exclude "README.md" ./ $USER@$SERVER:$WWW
  - ssh $USER@$SERVER "cd $WWW && chmod +x start.sh && ./start.sh"
 tags:
  - ai-group-runner
 when: on_success

